#!/usr/bin/env python3
"""Convert the original Robbo POKEY sound tables (TABS in d1/R1.ASM) to Game Boy
APU step sequences.

Each of the 15 sounds is 16 words `DTA A($AABB)`: AABB packs AUDF=$AA (POKEY
frequency divisor) in the high byte and AUDC=$BB (distortion+volume) in the low.
The original plays the 16 steps in REVERSE (step 15 first .. step 0 last),
advancing one step every 4 frames.

We emit, per sound, 16 steps x 3 bytes for the GB player:
  b0: bit7 = channel (0=square ch1, 1=noise ch4),  bits0-3 = volume (0..15)
  b1: square -> low 8 bits of the 11-bit frequency;  noise -> NR43 poly byte
  b2: square -> high 3 bits of the frequency;         noise -> 0
A step with volume 0 is silence.

POKEY pitch: with the default 64 kHz clock, f = 63920 / (2*(AUDF+1)).
GB square reg x: f = 131072/(2048-x)  ->  x = 2048 - 4.10*(AUDF+1).
POKEY distortion (AUDC bits 5-7): 5/6 are tonal -> GB square; 0/4 are noisy ->
GB noise (NR43 shift scaled from AUDF).
"""
import sys, os, re, math

NSOUNDS = 15
NSTEPS = 16
NAMES = ["explosion","shot","knock","teleport","screw","life","door","ammo",
         "push","key","destroy","enter","win","capsule","magnet"]

def parse_tabs(path):
    text = open(path, encoding="latin-1").read().splitlines()
    i = next(k for k, l in enumerate(text) if re.match(r'\s*TABS\s+EQU', l))
    words = []
    for l in text[i+1:]:
        m = re.search(r'DTA\s+A\(\$([0-9A-Fa-f]{4})\)', l)
        if m:
            words.append(int(m.group(1), 16))
            if len(words) == NSOUNDS * NSTEPS:
                break
    if len(words) != NSOUNDS * NSTEPS:
        raise SystemExit("expected %d words, got %d" % (NSOUNDS*NSTEPS, len(words)))
    return [words[s*NSTEPS:(s+1)*NSTEPS] for s in range(NSOUNDS)]

def gb_square_freq(audf):
    x = 2048 - int(round(4.10 * (audf + 1)))
    return max(0, min(2047, x))

def gb_noise_poly(audf):
    # match the POKEY noise clock (64kHz base, f = 31960/(AUDF+1)) to the GB
    # noise channel: f = 524288 / 2^(s+1) with divisor ratio r=1.
    fp = 31960.0 / (audf + 1)
    s = int(round(math.log2(524288.0 / fp))) - 1
    if s < 0: s = 0
    if s > 13: s = 13
    return (s << 4) | 0x01              # shift s, 15-bit width, divisor ratio 1

def step_bytes(word):
    audf = (word >> 8) & 0xFF
    audc = word & 0xFF
    vol = audc & 0x0F
    dist = (audc >> 5) & 7
    if vol == 0:
        return (0, 0, 0)                # silence
    # POKEY mixes 4 voices; on one GB channel its quiet effects (the box-push
    # 'skrzynia' is only volume 1-2) are inaudible, so scale volumes up.
    vol = min(15, vol * 2)
    if dist in (5, 6):                  # tonal -> square
        x = gb_square_freq(audf)
        return (vol, x & 0xFF, (x >> 8) & 0x07)
    else:                               # noisy (0/4) -> noise
        return (0x80 | vol, gb_noise_poly(audf), 0)

def main():
    src, outdir = sys.argv[1], sys.argv[2]
    sounds = parse_tabs(os.path.join(src, "d1", "R1.ASM"))
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "sounds.h"), "w") as h:
        h.write("#ifndef SOUNDS_H\n#define SOUNDS_H\n")
        h.write("/* generated by tools/convert_sound.py from R1.ASM TABS */\n")
        h.write("#define SND_NSTEPS %d\n" % NSTEPS)
        h.write("#define SND_COUNT %d\n" % NSOUNDS)
        h.write("/* per sound: %d steps x {b0:chan|vol, b1:freqlo/poly, b2:freqhi} */\n" % NSTEPS)
        h.write("static const unsigned char SND_SEQ[SND_COUNT][SND_NSTEPS*3] = {\n")
        for s in range(NSOUNDS):
            row = []
            for step in reversed(sounds[s]):      # original plays steps 15..0
                row += list(step_bytes(step))
            h.write("  { " + ",".join("0x%02X" % b for b in row) + " }, /* %s */\n" % NAMES[s])
        h.write("};\n#endif\n")
    print("sounds: %d x %d steps -> %s/sounds.h" % (NSOUNDS, NSTEPS, outdir))

if __name__ == "__main__":
    main()
