#!/usr/bin/env python3
r"""Emit Robbo's scrolling instruction text (English) for title.c.

The original Atari game shows Polish instructions with a vertical typewriter
scroll (see d1/TITLE.ASM, label INST).  Here we ship an English translation
followed by credits for the original edition, greedily word-wrapped to the
GBC's 20-column display width so words never split across the line break.  The one
hardware-specific control hint (the Atari "press ESC to give up") is localized
to the Game Boy equivalent (pause with START, choose RESTART).

Output: src/gen/instr.h  -  INSTR[][INSTR_WIDTH+1], one display line per row,
"" rows are paragraph spacers.  Run via the Makefile (argv: <orig> <outdir>);
<orig> is accepted for build-rule compatibility but unused.
"""
import sys, os, re

WRAP = 20   # display window width: the full GBC screen width, mirroring the
            # Atari's full-screen-width instruction window

# English instructions and original edition credits; '' = paragraph break.
PARAGRAPHS = [
    "INSTRUCTIONS",
    "",
    "ROBBO FACES A DIFFICULT JOURNEY ACROSS 56 PLANETS TO ESCAPE THE "
    "HOSTILE PLANETARY SYSTEM WHERE HE WAS TRICKED AND IMPRISONED.",
    "",
    "A SMALL CAPSULE AWAITS HIM ON EACH PLANET, READY TO CARRY HIM "
    "TO THE NEXT. UNFORTUNATELY, MOST CAPSULES ARE MISSING PARTS. "
    "ROBBO MUST COLLECT ENOUGH PARTS SCATTERED ACROSS THE PLANET TO "
    "REPAIR THEM.",
    "",
    "THE HOSTILE CREATURES THAT INHABIT THIS SYSTEM WILL TRY TO STOP HIM. "
    "ALONG THE WAY, ROBBO WILL FIND MANY DIFFERENT OBJECTS. DISCOVER "
    "WHAT THEY DO: TRY PUSHING THEM, PICKING THEM UP, OR SHOOTING THEM.",
    "",
    "IF ROBBO GETS STUCK WITH NO WAY OUT, PRESS START AND CHOOSE RESTART.",
    "",
    "REMEMBER: EVERY PLANET CAN BE COMPLETED!",
    "",
    "HAVE FUN! - THE AUTHOR",
    "",
    "THE ORIGINAL ATARI XL AND XE EDITION WAS RELEASED IN 1989. "
    "IT WAS CREATED BY JANUSZ PELC AND PUBLISHED BY LK AVALON.",
]

def wrap(text, width):
    """greedy word-wrap; hard-split only words longer than the window."""
    lines, cur = [], ""
    for w in text.split():
        while len(w) > width:                  # overlong token: hard split
            if cur:
                lines.append(cur); cur = ""
            lines.append(w[:width]); w = w[width:]
        if not cur:
            cur = w
        elif len(cur) + 1 + len(w) <= width:
            cur += " " + w
        else:
            lines.append(cur); cur = w
    if cur:
        lines.append(cur)
    return lines

def build_lines():
    lines = []
    for para in PARAGRAPHS:
        if para == "":
            if lines and lines[-1] != "":
                lines.append("")
            continue
        lines.extend(wrap(para, WRAP))
    while lines and lines[0] == "": lines.pop(0)
    while lines and lines[-1] == "": lines.pop()
    # centre the INSTRUCTIONS heading in the window (the Atari centres its
    # inverse-video label); menu.c renders line 0's non-space glyphs inverse.
    if lines and lines[0] == "INSTRUCTIONS":
        lines[0] = " " * ((WRAP - len(lines[0])) // 2) + lines[0]
    return lines

def main():
    outdir = sys.argv[2] if len(sys.argv) > 2 else sys.argv[1]
    lines = build_lines()
    longest = max(len(l) for l in lines)
    assert longest <= WRAP, "line exceeds window width: %r" % \
        next(l for l in lines if len(l) > WRAP)
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "instr.h"), "w") as h:
        h.write("#ifndef INSTR_H\n#define INSTR_H\n")
        h.write("/* generated by tools/extract_instr.py - do not edit */\n")
        h.write("#define INSTR_WIDTH %d\n" % WRAP)
        h.write("#define INSTR_NLINES %d\n" % len(lines))
        h.write("static const char INSTR[INSTR_NLINES][INSTR_WIDTH+1] = {\n")
        for ln in lines:
            esc = ln.replace("\\", "\\\\").replace('"', '\\"')
            h.write('  "%s",\n' % esc)
        h.write("};\n#endif\n")
    print("instr: %d lines (width %d, longest %d) -> %s/instr.h"
          % (len(lines), WRAP, longest, outdir))

if __name__ == "__main__":
    main()
