#!/usr/bin/env python3
r"""Emit Robbo's scrolling instruction text (English) for title.c.

The original Atari game shows a Polish instruction with a vertical typewriter
scroll in a 12-column window (see d1/TITLE.ASM, label INST).  Here we ship a
faithful ENGLISH translation of that text, greedily word-wrapped to the same
12-column display width so words never split across the line break.  The one
hardware-specific control hint (the Atari "press ESC to give up") is localized
to the Game Boy equivalent (pause with START, choose RESTART).

Output: src/gen/instr.h  -  INSTR[][INSTR_WIDTH+1], one display line per row,
"" rows are paragraph spacers.  Run via the Makefile (argv: <orig> <outdir>);
<orig> is accepted for build-rule compatibility but unused.
"""
import sys, os, re

WRAP = 20   # display window width: the full GBC screen width, mirroring the
            # Atari's full-screen-width instruction window

# Faithful English translation of the original instruction; '' = paragraph break.
PARAGRAPHS = [
    "INSTRUCTIONS",
    "",
    "ROBBO MUST CROSS A HARD ROAD THROUGH 56 PLANETS TO ESCAPE THE "
    "HOSTILE PLANET SYSTEM IN WHICH HE WAS CUNNINGLY IMPRISONED.",
    "",
    "ON EACH PLANET A SMALL CAPSULE WAITS FOR HIM, ABLE TO FLY TO THE "
    "NEXT PLANET. SADLY, MOST CAPSULES ARE INCOMPLETE, SO ROBBO MUST "
    "GATHER ENOUGH PARTS SCATTERED OVER THE PLANET. EVIL CREATURES, "
    "THE LOCALS OF THE SYSTEM, WILL BLOCK HIS WAY. ON HIS TREK ROBBO "
    "FINDS MANY OBJECTS. LEARN WHAT THEY DO. TRY TO PUSH, GATHER OR "
    "SHOOT THEM.",
    "",
    "IF ROBBO GETS STUCK WITH NO WAY OUT, PRESS START TO RESTART THE PLANET.",
    "",
    "REMEMBER, EVERY PLANET CAN BE BEATEN!",
    "",
    "HAVE FUN! - THE AUTHOR",
]

def wrap(text, width):
    """greedy word-wrap; hard-split only words longer than the window."""
    lines, cur = [], ""
    for w in text.split():
        while len(w) > width:                  # overlong token: hard split
            if cur:
                lines.append(cur); cur = ""
            lines.append(w[:width]); w = w[width:]
        if not cur:
            cur = w
        elif len(cur) + 1 + len(w) <= width:
            cur += " " + w
        else:
            lines.append(cur); cur = w
    if cur:
        lines.append(cur)
    return lines

def build_lines():
    lines = []
    for para in PARAGRAPHS:
        if para == "":
            if lines and lines[-1] != "":
                lines.append("")
            continue
        lines.extend(wrap(para, WRAP))
    while lines and lines[0] == "": lines.pop(0)
    while lines and lines[-1] == "": lines.pop()
    # centre the INSTRUCTIONS heading in the window (the Atari centres its
    # inverse-video label); menu.c renders line 0's non-space glyphs inverse.
    if lines and lines[0] == "INSTRUCTIONS":
        lines[0] = " " * ((WRAP - len(lines[0])) // 2) + lines[0]
    return lines

def main():
    outdir = sys.argv[2] if len(sys.argv) > 2 else sys.argv[1]
    lines = build_lines()
    longest = max(len(l) for l in lines)
    assert longest <= WRAP, "line exceeds window width: %r" % \
        next(l for l in lines if len(l) > WRAP)
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "instr.h"), "w") as h:
        h.write("#ifndef INSTR_H\n#define INSTR_H\n")
        h.write("/* generated by tools/extract_instr.py - do not edit */\n")
        h.write("#define INSTR_WIDTH %d\n" % WRAP)
        h.write("#define INSTR_NLINES %d\n" % len(lines))
        h.write("static const char INSTR[INSTR_NLINES][INSTR_WIDTH+1] = {\n")
        for ln in lines:
            esc = ln.replace("\\", "\\\\").replace('"', '\\"')
            h.write('  "%s",\n' % esc)
        h.write("};\n#endif\n")
    print("instr: %d lines (width %d, longest %d) -> %s/instr.h"
          % (len(lines), WRAP, longest, outdir))

if __name__ == "__main__":
    main()
