#!/usr/bin/env python3
"""Generate src/atari_pal.c (gr_atari_pal) from the authentic Atari per-level
colours.

Each Atari level's colour registers live in the d2/C*.txt `metadata:` line
(CAPA bytes): byte2=COLPF0, byte3=COLPF1, byte4=COLPF2, byte5=COLPF3,
byte6=COLBK, byte7=COLB.  The GBC tile palettes (verified against the emulator
on several levels) are:
    palette 0 (normal glyphs) = [COLB, COLPF0, COLPF1, COLPF2]
    palette 1 (inverse=walls) = [COLB, COLPF0, COLPF1, COLPF3]
(idx0 = the value-0 "floor"/background inside a tile = COLB, NOT COLBK.)

Each Atari colour byte -> RGB via the atari800 NTSC palette in
tools/atari_ntsc_palette.txt (extracted once with a colour-chart ROM), then
RGB888 -> GBC BGR555 = (r>>3) | (g>>3)<<5 | (b>>3)<<10.

Usage: gen_atari_pal.py ATARI_D2_DIR > src/atari_pal.c
"""
import sys, os, re

def load_ntsc(path):
    pal = {}
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        cb, r, g, b = line.split()
        pal[int(cb, 16)] = (int(r), int(g), int(b))
    return pal

def bgr555(rgb):
    r, g, b = rgb
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)

def parse_metadata(d2dir):
    """level number (1..56, in C1|C2|C3 order) -> list of CAPA bytes."""
    out, n = {}, 0
    for f in ("C1", "C2", "C3"):
        for line in open(f"{d2dir}/{f}.txt", encoding="utf-8"):
            m = re.match(r"metadata:\s*([0-9a-fA-F]+)", line)
            if m:
                n += 1
                hx = m.group(1)
                out[n] = [int(hx[i:i+2], 16) for i in range(0, len(hx), 2)]
    return out

def main():
    d2dir = sys.argv[1]
    ntsc = load_ntsc(os.path.join(os.path.dirname(__file__), "atari_ntsc_palette.txt"))
    meta = parse_metadata(d2dir)

    def c(byte):
        return bgr555(ntsc[byte])

    rows, colbk = [], []
    for lv in range(1, 57):
        b = meta[lv]
        COLPF0, COLPF1, COLPF2, COLPF3, COLBK, COLB = b[2], b[3], b[4], b[5], b[6], b[7]
        pal = [c(COLB), c(COLPF0), c(COLPF1), c(COLPF2),
               c(COLB), c(COLPF0), c(COLPF1), c(COLPF3)]
        rows.append("  {" + ",".join("0x%04X" % v for v in pal) + "}, /* %d */" % lv)
        colbk.append("0x%04X" % c(COLBK))

    print("/* Per-level Atari palettes (BGR555).  [0..3]=normal glyphs, [4..7]=inverse")
    print("   (walls).  Indexed by level number-1.  GENERATED by tools/gen_atari_pal.py")
    print("   from the d2/C*.txt `metadata:` colour bytes through the atari800 NTSC")
    print("   palette (tools/atari_ntsc_palette.txt) - DO NOT hand-edit. */")
    print("#pragma bank 255")
    print("#include <gb/gb.h>")
    print('#include "levels_data.h"')
    print("BANKREF(gr_atari_pal)")
    print("const unsigned int gr_atari_pal[GR_NLEVELS][8] = {")
    print("\n".join(rows))
    print("};")
    print("/* COLBK per level: the black inner-cave fill colour (Atari `┼`).")
    print("   Same bank as gr_atari_pal (read it under BANK(gr_atari_pal)). */")
    print("const unsigned int gr_atari_colbk[GR_NLEVELS] = {")
    print("  " + ",".join(colbk) + "};")

if __name__ == "__main__":
    main()
